[build]
 command = "npm run build"
publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  DATABASE_URL = "postgresql://postgres.awihyqbivrlsctaaviaf:y6xx2ymbRLmjUvrL@aws-0-us-east-2.pooler.supabase.com:6543/postgres"